<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Cliente>
 */
class ClienteFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition()
    {
        return [
          'dui_cliente' => $this->faker->unique()->regexify('^\d{9}$'),
          'primer_nom_cliente' => 'Juan',
          'segundo_nom_cliente' => 'Pablo',
          'primer_ape_cliente' => 'Perez',
          'segundo_ape_cliente' => 'Lopez',
          'fech_nac_cliente' => $this->faker->date(),
          'dir_cliente' => $this->faker->address(),
          'email_cliente' => $this->faker->email(),
          'estado_civil_cliente' => 'Divorciado',
          'tipo_vivienda_cliente' => 'Propia',
          'ocupacion_cliente' => 'Empleado',
          'gasto_aliment_cliente' => $this->faker->numberBetween(1,100),
          'gasto_agua_cliente' => $this->faker->numberBetween(1,100),
          'gasto_luz_cliente' => $this->faker->numberBetween(1,100),
          'gasto_cable_cliente' => $this->faker->numberBetween(1,100),
          'gasto_vivienda_cliente' => $this->faker->numberBetween(1,100),
          'gasto_otro_cliente' => $this->faker->numberBetween(1,100),
          'estado_cliente' => 'Activo',
          'created_at' => $this->faker->dateTime(),
          'updated_at' => $this->faker->dateTime(),

          'dui_cliente' => $this->faker->unique()->regexify('^\d{9}$'),
          'primer_nom_cliente' => 'Mario',
          'segundo_nom_cliente' => 'Pablo',
          'primer_ape_cliente' => 'Zelaya',
          'segundo_ape_cliente' => 'Landaverde',
          'fech_nac_cliente' => $this->faker->date(),
          'dir_cliente' => $this->faker->address(),
          'email_cliente' => $this->faker->email(),
          'estado_civil_cliente' => 'Soltero',
          'tipo_vivienda_cliente' => 'Familiar',
          'ocupacion_cliente' => 'Independiente',
          'gasto_aliment_cliente' => $this->faker->numberBetween(1,100),
          'gasto_agua_cliente' => $this->faker->numberBetween(1,100),
          'gasto_luz_cliente' => $this->faker->numberBetween(1,100),
          'gasto_cable_cliente' => $this->faker->numberBetween(1,100),
          'gasto_vivienda_cliente' => $this->faker->numberBetween(1,100),
          'gasto_otro_cliente' => $this->faker->numberBetween(1,100),
          'estado_cliente' => 'Activo',
          'created_at' => $this->faker->dateTime(),
          'updated_at' => $this->faker->dateTime(),

          'dui_cliente' => $this->faker->unique()->regexify('^\d{9}$'),
          'primer_nom_cliente' => 'Sergio',
          'segundo_nom_cliente' => 'Rafael',
          'primer_ape_cliente' => 'Martinez',
          'segundo_ape_cliente' => 'Garcia',
          'fech_nac_cliente' => $this->faker->date(),
          'dir_cliente' => $this->faker->address(),
          'email_cliente' => $this->faker->email(),
          'estado_civil_cliente' => 'Casado o Unión Libre',
          'tipo_vivienda_cliente' => 'Familiar',
          'ocupacion_cliente' => 'Comerciante',
          'gasto_aliment_cliente' => $this->faker->numberBetween(1,100),
          'gasto_agua_cliente' => $this->faker->numberBetween(1,100),
          'gasto_luz_cliente' => $this->faker->numberBetween(1,100),
          'gasto_cable_cliente' => $this->faker->numberBetween(1,100),
          'gasto_vivienda_cliente' => $this->faker->numberBetween(1,100),
          'gasto_otro_cliente' => $this->faker->numberBetween(1,100),
          'estado_cliente' => 'Activo',
          'created_at' => $this->faker->dateTime(),
          'updated_at' => $this->faker->dateTime(),

          'dui_cliente' => $this->faker->unique()->regexify('^\d{9}$'),
          'primer_nom_cliente' => 'Ana',
          'segundo_nom_cliente' => 'Maria',
          'primer_ape_cliente' => 'Garcia',
          'segundo_ape_cliente' => 'Flores',
          'fech_nac_cliente' => $this->faker->date(),
          'dir_cliente' => $this->faker->address(),
          'email_cliente' => $this->faker->email(),
          'estado_civil_cliente' => 'Soltero',
          'tipo_vivienda_cliente' => 'Alquilada',
          'ocupacion_cliente' => 'Empresario',
          'gasto_aliment_cliente' => $this->faker->numberBetween(1,100),
          'gasto_agua_cliente' => $this->faker->numberBetween(1,100),
          'gasto_luz_cliente' => $this->faker->numberBetween(1,100),
          'gasto_cable_cliente' => $this->faker->numberBetween(1,100),
          'gasto_vivienda_cliente' => $this->faker->numberBetween(1,100),
          'gasto_otro_cliente' => $this->faker->numberBetween(1,100),
          'estado_cliente' => 'Activo',
          'created_at' => $this->faker->dateTime(),
          'updated_at' => $this->faker->dateTime(),

          'dui_cliente' => $this->faker->unique()->regexify('^\d{9}$'),
          'primer_nom_cliente' => 'Juan',
          'segundo_nom_cliente' => 'Gonzalo',
          'primer_ape_cliente' => 'Rodriguez',
          'segundo_ape_cliente' => 'Castro',
          'fech_nac_cliente' => $this->faker->date(),
          'dir_cliente' => $this->faker->address(),
          'email_cliente' => $this->faker->email(),
          'estado_civil_cliente' => 'Casado o Unión Libre',
          'tipo_vivienda_cliente' => 'Familiar',
          'ocupacion_cliente' => 'Maestro',
          'gasto_aliment_cliente' => $this->faker->numberBetween(1,100),
          'gasto_agua_cliente' => $this->faker->numberBetween(1,100),
          'gasto_luz_cliente' => $this->faker->numberBetween(1,100),
          'gasto_cable_cliente' => $this->faker->numberBetween(1,100),
          'gasto_vivienda_cliente' => $this->faker->numberBetween(1,100),
          'gasto_otro_cliente' => $this->faker->numberBetween(1,100),
          'estado_cliente' => 'Activo',
          'created_at' => $this->faker->dateTime(),
          'updated_at' => $this->faker->dateTime(),

          'dui_cliente' => $this->faker->unique()->regexify('^\d{9}$'),
          'primer_nom_cliente' => 'Walter',
          'segundo_nom_cliente' => 'Antonio',
          'primer_ape_cliente' => 'Martinez',
          'segundo_ape_cliente' => 'Quintanilla',
          'fech_nac_cliente' => $this->faker->date(),
          'dir_cliente' => $this->faker->address(),
          'email_cliente' => $this->faker->email(),
          'estado_civil_cliente' => 'Soltero',
          'tipo_vivienda_cliente' => 'Alquilada',
          'ocupacion_cliente' => 'Independiente',
          'gasto_aliment_cliente' => $this->faker->numberBetween(1,100),
          'gasto_agua_cliente' => $this->faker->numberBetween(1,100),
          'gasto_luz_cliente' => $this->faker->numberBetween(1,100),
          'gasto_cable_cliente' => $this->faker->numberBetween(1,100),
          'gasto_vivienda_cliente' => $this->faker->numberBetween(1,100),
          'gasto_otro_cliente' => $this->faker->numberBetween(1,100),
          'estado_cliente' => 'Activo',
          'created_at' => $this->faker->dateTime(),
          'updated_at' => $this->faker->dateTime(),

          'dui_cliente' => $this->faker->unique()->regexify('^\d{9}$'),
          'primer_nom_cliente' => 'Daniel',
          'segundo_nom_cliente' => 'Louis',
          'primer_ape_cliente' => 'Tomas',
          'segundo_ape_cliente' => 'Garcia',
          'fech_nac_cliente' => $this->faker->date(),
          'dir_cliente' => $this->faker->address(),
          'email_cliente' => $this->faker->email(),
          'estado_civil_cliente' => 'Viudo',
          'tipo_vivienda_cliente' => 'Alquilada',
          'ocupacion_cliente' => 'Joyero',
          'gasto_aliment_cliente' => $this->faker->numberBetween(1,100),
          'gasto_agua_cliente' => $this->faker->numberBetween(1,100),
          'gasto_luz_cliente' => $this->faker->numberBetween(1,100),
          'gasto_cable_cliente' => $this->faker->numberBetween(1,100),
          'gasto_vivienda_cliente' => $this->faker->numberBetween(1,100),
          'gasto_otro_cliente' => $this->faker->numberBetween(1,100),
          'estado_cliente' => 'Activo',
          'created_at' => $this->faker->dateTime(),
          'updated_at' => $this->faker->dateTime(),

          'dui_cliente' => $this->faker->unique()->regexify('^\d{9}$'),
          'primer_nom_cliente' => 'Karla',
          'segundo_nom_cliente' => 'Beatriz',
          'primer_ape_cliente' => 'Ortiz',
          'segundo_ape_cliente' => 'Rodriguez',
          'fech_nac_cliente' => $this->faker->date(),
          'dir_cliente' => $this->faker->address(),
          'email_cliente' => $this->faker->email(),
          'estado_civil_cliente' => 'Casado o Unión Libre',
          'tipo_vivienda_cliente' => 'Familiar',
          'ocupacion_cliente' => 'Trabajador Social',
          'gasto_aliment_cliente' => $this->faker->numberBetween(1,100),
          'gasto_agua_cliente' => $this->faker->numberBetween(1,100),
          'gasto_luz_cliente' => $this->faker->numberBetween(1,100),
          'gasto_cable_cliente' => $this->faker->numberBetween(1,100),
          'gasto_vivienda_cliente' => $this->faker->numberBetween(1,100),
          'gasto_otro_cliente' => $this->faker->numberBetween(1,100),
          'estado_cliente' => 'Inactivo',
          'created_at' => $this->faker->dateTime(),
          'updated_at' => $this->faker->dateTime(),

          'dui_cliente' => $this->faker->unique()->regexify('^\d{9}$'),
          'primer_nom_cliente' => 'Sandra',
          'segundo_nom_cliente' => 'Vanessa',
          'primer_ape_cliente' => 'Martinez',
          'segundo_ape_cliente' => 'Garcia',
          'fech_nac_cliente' => $this->faker->date(),
          'dir_cliente' => $this->faker->address(),
          'email_cliente' => $this->faker->email(),
          'estado_civil_cliente' => 'Soltero',
          'tipo_vivienda_cliente' => 'Alquilada',
          'ocupacion_cliente' => 'Veterinaria',
          'gasto_aliment_cliente' => $this->faker->numberBetween(1,100),
          'gasto_agua_cliente' => $this->faker->numberBetween(1,100),
          'gasto_luz_cliente' => $this->faker->numberBetween(1,100),
          'gasto_cable_cliente' => $this->faker->numberBetween(1,100),
          'gasto_vivienda_cliente' => $this->faker->numberBetween(1,100),
          'gasto_otro_cliente' => $this->faker->numberBetween(1,100),
          'estado_cliente' => 'Inactivo',
          'created_at' => $this->faker->dateTime(),
          'updated_at' => $this->faker->dateTime(),

          'dui_cliente' => $this->faker->unique()->regexify('^\d{9}$'),
          'primer_nom_cliente' => 'Cindy',
          'segundo_nom_cliente' => 'Daniela',
          'primer_ape_cliente' => 'Garcia',
          'segundo_ape_cliente' => 'Castro',
          'fech_nac_cliente' => $this->faker->date(),
          'dir_cliente' => $this->faker->address(),
          'email_cliente' => $this->faker->email(),
          'estado_civil_cliente' => 'Soltero',
          'tipo_vivienda_cliente' => 'Alquilada',
          'ocupacion_cliente' => 'Ventas y Marketing',
          'gasto_aliment_cliente' => $this->faker->numberBetween(1,100),
          'gasto_agua_cliente' => $this->faker->numberBetween(1,100),
          'gasto_luz_cliente' => $this->faker->numberBetween(1,100),
          'gasto_cable_cliente' => $this->faker->numberBetween(1,100),
          'gasto_vivienda_cliente' => $this->faker->numberBetween(1,100),
          'gasto_otro_cliente' => $this->faker->numberBetween(1,100),
          'estado_cliente' => 'Inactivo',
          'created_at' => $this->faker->dateTime(),
          'updated_at' => $this->faker->dateTime(),
        ];
    }
}
